name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./Production/pom.xml
          mvn clean package -f ./Material Management/pom.xml
          mvn clean package -f ./Manufacturing Management/pom.xml
          mvn clean package -f ./Sales/pom.xml
          mvn clean package -f ./Standard Management/pom.xml

      - name: Docker Build and push for Production
        uses: docker/build-push-action@v4
        with:
          context: ./Production
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/production:latest
            ghcr.io/${{ github.repository }}/production:${{ github.ref_name }}
            
      - name: Docker Build and push for MaterialManagement
        uses: docker/build-push-action@v4
        with:
          context: ./Material Management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/material-management:latest
            ghcr.io/${{ github.repository }}/material-management:${{ github.ref_name }}
            
      - name: Docker Build and push for ManufacturingManagement
        uses: docker/build-push-action@v4
        with:
          context: ./Manufacturing Management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/manufacturing-management:latest
            ghcr.io/${{ github.repository }}/manufacturing-management:${{ github.ref_name }}
            
      - name: Docker Build and push for Sales
        uses: docker/build-push-action@v4
        with:
          context: ./Sales
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/sales:latest
            ghcr.io/${{ github.repository }}/sales:${{ github.ref_name }}
            
      - name: Docker Build and push for StandardManagement
        uses: docker/build-push-action@v4
        with:
          context: ./Standard Management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/standard-management:latest
            ghcr.io/${{ github.repository }}/standard-management:${{ github.ref_name }}
            
