---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Production
  labels:
    app: Production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Production
  template:
    metadata:
      labels:
        app: Production
    spec:
      containers:
        - name: Production
          image: username/Production:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Material Management
  labels:
    app: Material Management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Material Management
  template:
    metadata:
      labels:
        app: Material Management
    spec:
      containers:
        - name: Material Management
          image: username/Material Management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Manufacturing Management
  labels:
    app: Manufacturing Management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Manufacturing Management
  template:
    metadata:
      labels:
        app: Manufacturing Management
    spec:
      containers:
        - name: Manufacturing Management
          image: username/Manufacturing Management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Sales
  labels:
    app: Sales
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Sales
  template:
    metadata:
      labels:
        app: Sales
    spec:
      containers:
        - name: Sales
          image: username/Sales:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Standard Management
  labels:
    app: Standard Management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Standard Management
  template:
    metadata:
      labels:
        app: Standard Management
    spec:
      containers:
        - name: Standard Management
          image: username/Standard Management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Production
  labels:
    app: Production
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Production


---


apiVersion: v1
kind: Service
metadata:
  name: Material Management
  labels:
    app: Material Management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Material Management


---


apiVersion: v1
kind: Service
metadata:
  name: Manufacturing Management
  labels:
    app: Manufacturing Management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Manufacturing Management


---


apiVersion: v1
kind: Service
metadata:
  name: Sales
  labels:
    app: Sales
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Sales


---


apiVersion: v1
kind: Service
metadata:
  name: Standard Management
  labels:
    app: Standard Management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Standard Management

